package com.dummy.potter.rest_tutorial.event.listeners;

import com.dummy.potter.rest_tutorial.event.CustomEvent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.ApplicationListener;
import org.springframework.stereotype.Component;

/**
 * @param <T>
 *     if not extend your custom event, it will receive all events generated by the spring
 */
@Component
public class CustomEventListener<T extends CustomEvent> implements ApplicationListener<T> {
    final static Logger logger = LoggerFactory.getLogger(CustomEventListener.class);
    @Override
    public void onApplicationEvent(T event) {
        logger.info("Caught event: {}", event);
    }
}
